version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: credef
      MYSQL_USER: credef
      MYSQL_PASSWORD: credef
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    # Retirer la ligne "command:" qui posait problème
  adminer:
    image: adminer
    ports:
      - "8080:8080"
